#!/bin/bash

# The post-receive hook is called after receive-pack has accepted a pack and the
# repository has been updated. It is passed arguments in through stdin in the
# form "oldrev newrev refname".

# Read the input
while read oldrev newrev refname
do
  echo "Old revision: $oldrev"
  echo "New revision: $newrev"
  echo "Ref name: $refname"

  # Do something based on the branch name
  if [[ $refname == "refs/heads/main" ]]; then
    echo "The main branch was updated."
    
    cd ~/apps/pixelparade.xyz
    
    echo "Deploying main branch to production..."
    
    git --work-tree=$HOME/apps/pixelparade.xyz \
        --git-dir=$HOME/repos/pixelparade.git \
        checkout -f main

    echo "Restarting services..."
    
    docker compose \
      -f docker-compose.yml \
      -f docker-compose.production.yml \
      up --build --force-recreate -d

    echo "Services restarted."

    docker compose \
      -f docker-compose.yml \
      -f docker-compose.production.yml \
      ls

    docker compose \
      -f docker-compose.yml \
      -f docker-compose.production.yml \
      ps

    # Add custom logic here for when the main branch is updated
  elif [[ $refname == "refs/tags/"* ]]; then
    echo "A tag was updated/created."
    # Add custom logic here for when a tag is updated/created
  else
    echo "Some other ref was updated."
    # Add custom logic here for other refs
  fi
done

# Add any additional logic needed after all the updates have been processed

# End of script
