#!/bin/bash

while read oldrev newrev ref
do
if [[ $ref =~ .*/main$ ]];
then
echo "Deploying main branch to production..."
else
echo "Ref $ref successfully received, but only the main branch will be deployed."
fi
done